name: Staging Deployment

concurrency: staging

on:
  push:
    branches:
      - "dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: beta@167.71.113.24
          remote-user: beta
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.PATH }}
          rsync-options: --dry-run