name: staging-deploy
on:
  push:
    branches:
      - "dev/**"

jobs:
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Deploy via SFTP
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            protocol: ftps
            server: ${{ secrets.SFTP_URL }}
            local-dir: ${{ secrets.SFTP_STAGING_PATH }}
            username: ${{ secrets.SFTP_STAGING_USER }}
            password: ${{ secrets.SFTP_STAGING_PASSWORD }}
            exclude: |
              **/node_modules/**
